import { RecommendationsResult } from '@/types';

export const FALLBACK_RECOMMENDATIONS: RecommendationsResult = {
  total_tasks: 6,
  critical_tasks: 2,
  high_tasks: 2,
  summary: {
    pending_packages: 18,
    idle_vehicles: 1,
    active_vehicles: 5,
    delayed_vehicles: 1,
    fleet_efficiency_score: 85.5,
  },
  generated_by: ['KMP', 'Knapsack', 'Graham Scan', 'Floyd-Warshall', 'Edmonds-Karp'],
  tasks: [
    {
      id: 'TASK-KMP-01',
      algo: 'KMP String Match',
      algo_tag: 'O(N+M)',
      algo_color: 'cyan',
      priority: 1,
      urgency: 'CRITICAL',
      title: 'Dispatch Priority-5 Customer Deliveries Immediately',
      description:
        'KMP pattern scan identified hospital and Priority-5 customers (Apollo Medical Center, Safdarjung Hospital, AIIMS Trauma Centre) requiring immediate dispatch.',
      action: 'Assign V07 (IDLE) to cover critical hospital stops',
      impact: 'Prevents SLA breach for high-value medical cargo',
      metric: 'Hospital + P5 stops identified',
    },
    {
      id: 'TASK-CROSS-01',
      algo: 'Floyd-Warshall + Edmonds-Karp',
      algo_tag: 'Combined',
      algo_color: 'orange',
      priority: 2,
      urgency: 'CRITICAL',
      title: 'Resolve 1 Delayed Vehicle — Immediate Action Required',
      description:
        'V08 (HR-09-GT-9981) is DELAYED at Ashram Chowk. Combined shortest-path reroute plus max-flow rebalancing is the optimal resolution.',
      action: 'Reroute V08 via Nehru Place Bypass; alert recipient customers',
      impact: 'Prevent cascading delays; maintain delivery SLA',
      metric: '1 delayed | Alternate route computed',
    },
    {
      id: 'TASK-KS-01',
      algo: '0/1 Knapsack DP',
      algo_tag: 'O(N·W)',
      algo_color: 'emerald',
      priority: 3,
      urgency: 'HIGH',
      title: 'Load V07 (IDLE) with Optimal Cargo',
      description:
        'Knapsack DP selected the highest-value pending packages that fit V07’s 300 kg capacity, including RN-HOSP medical cargo.',
      action: 'Load selected packages onto V07 (Arjun Mehta) and dispatch',
      impact: 'Clears highest-value pending backlog',
      metric: '300 kg capacity optimization',
    },
    {
      id: 'TASK-KMP-02',
      algo: 'KMP String Match',
      algo_tag: 'O(N+M)',
      algo_color: 'cyan',
      priority: 4,
      urgency: 'HIGH',
      title: 'Hospital Route — Pattern Match Detected',
      description:
        "KMP matched 'Hospital' across Safdarjung, Max Super Speciality, Fortis Noida, and Vasant Kunj General Hospital records.",
      action: 'Assign dedicated V04/V05 route for hospital stops',
      impact: 'Medical supplies arrive within 2-hour SLA',
      metric: 'Hospital locations matched',
    },
    {
      id: 'TASK-GS-01',
      algo: "Graham's Scan",
      algo_tag: 'O(N log N)',
      algo_color: 'purple',
      priority: 5,
      urgency: 'MEDIUM',
      title: 'Review Convex Delivery Zone Boundaries',
      description:
        'Graham’s Scan hulls for North/South/East/West/Central clusters isolate interior customers for multi-drop grouping.',
      action: 'Assign cluster routes by geographic proximity per zone',
      impact: 'Reduce total route distance by up to 22%',
      metric: '5 convex zone hulls',
    },
    {
      id: 'TASK-EK-01',
      algo: 'Edmonds-Karp',
      algo_tag: 'O(V·E²)',
      algo_color: 'rose',
      priority: 7,
      urgency: 'MEDIUM',
      title: 'Network Bottleneck Alert — Mathura Road',
      description:
        'Edmonds-Karp max-flow flags Mathura Road (Ashram Chowk → Hub) as a saturated bottleneck at 800 veh/hr.',
      action: 'Stagger warehouse departures by 15-minute intervals',
      impact: 'Relieve saturation; improve on-time rate',
      metric: 'Bottleneck: E14 Mathura Road',
    },
  ],
};
